### ISSUE TITLE
有没有详细的安装说明

### ISSUE THREAD

**Issue by wms3001** [honraytech/VueThink#1]
npm run dev   报错
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Home.vue
Module not found: Error: Cannot resolve 'file' or 'directory' ./account/changePwd.vue in /opt/lampp/htdocs/frontEnd/src/components
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Home.vue 11:17-51
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0
webpack: Failed to compile.

**Comment by Leungkingman** [comment]
@wms3001 前端的部署就两个步骤，代码拉下来之后npm install，依赖安装完成之后npm run dev 就可以了，后端的配置可以看一下这里：https://github.com/honraytech/VueThink/tree/master/php

**Comment by zhizhi2017** [comment]
@Leungkingman 1，安装后npm run dev，打开localhost：8080 提示 服务超时 。
2，后端配置？？？一脸懵。
3，按照以前建站的经验，在本地建站后，www.aaa.com 打开网址空白一片！！！

**Comment by Leungkingman** [comment]
@zhizhi2017 因为你本地的后端服务没有启动，所以请求的地址"http://localhost:80"不存在会提示请求失败。

**Comment by helinyu** [comment]
??? 是不是将你的和这个源码下载下来？架构就好了的？

**Comment by Leungkingman** [comment]
@helinyu 前后端分离的架构都是两套的，后端一套，前端一套。

**Comment by AngQin104** [comment]
> @Leungkingman 1，安装后npm run dev，打开localhost：8080 提示 服务超时 。 2，后端配置？？？一脸懵。 3，按照以前建站的经验，在本地建站后，www.aaa.com 打开网址空白一片！！！

后端启动了还是这样的问题
