### ISSUE TITLE
搭建后问题

### ISSUE THREAD

**Issue by zhizhi2017** [honraytech/VueThink#3]
搭建成功了，就是有一点问题：登录成功后跳转直接是www.xx.com/users/list，只显示蓝色背景。我在vuex/routes.js里面把路径path: 'users/list' 改成path: '/users/list' ，登陆后就正常了。并且改了所有的children path。
但是总觉得这样不对，不知道该怎么办？   ps：搭建后台的时候目录文件是  d:\vuethink\php

**Comment by Leungkingman** [comment]
@zhizhi2017 这个是sql的路由数据不是最新而导致的，现在已经更新了，谢谢提醒
