### ISSUE TITLE
登陆后台时，跨域的问题如何解决？

### ISSUE THREAD

**Issue by hansoy** [honraytech/VueThink#8]
` XMLHttpRequest cannot load http://localhost/admin/base/getConfigs. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
http.js?fff4:22 f Error: Network Error
    at createError (eval at <anonymous> (app.js:1452), <anonymous>:15:15)
    at XMLHttpRequest.handleError (eval at <anonymous> (app.js:1434), <anonymous>:87:14)
http.js?fff4:104 default error
getVerify:1 GET http://localhost/admin/base/getVerify 404 (Not Found)`

Access-Control-Allow-Origin 跨域的问题如何解决？谢谢...

**Comment by svcgv** [comment]
传入参数增加 HttpServletResponse response    

方法内增加response.setHeader("Access-Control-Allow-Origin", "*");
